### ISSUE TITLE
Using files instead of bundle metadata can create invalid manifest

### ISSUE THREAD

**Issue by gbirke** [pierredavidbelanger/parcel-plugin-appcache#1]
If your `dist` directory contains files from previous runs of parcel (maybe you forget to stop the parcel dev server before building for production), your manifest will not work because browsers ignore manifests with files that don't exist.

A workaround for this behavior would be to delete the contents of the `dist` directory before running `parcel build`.

My suggestion would be to use the `assets` and `childBundles` properties of the bundle parameter instead.

**Comment by pierredavidbelanger** [comment]
You are right! It make sense.
Are you able to submit a patch for this?

**Comment by gbirke** [comment]
After having looked into it, I'm not so sure of my suggested change any more. We would have to change the `appcache-manifest` library first, because it operates on globbed files and not on file lists. I've opened an issue: https://github.com/mysticatea/appcache-manifest/issues/8

I'd be able to provide a patch for this.

**Comment by pierredavidbelanger** [comment]
If I understand correctly, the [`fileGlobs` parameter](https://github.com/mysticatea/appcache-manifest#amgeneratefileglobs-options) can be an `string[]`, and a globs does not **need** to contains wildcards and all...

So, I guess even without fixing `appcache-manifest`, we can only list all files we want to include into the `fileGlobs` parameter and it should work.

What do you think ?

**Comment by gbirke** [comment]
Of course! That's much easier. I'll see if I can find the time this week for a pull request.
