### ISSUE TITLE
Plugin fails when using multiple entry points

### ISSUE THREAD

**Issue by gbirke** [pierredavidbelanger/parcel-plugin-appcache#3]
While working and manually testing #2 , I saw that if you run the command with multiple entry points, e.g. `parcel index1.html index2.html` the plugin will fail with the error

    The "path" argument must be of type string. Received type undefined

I don't use multiple entry points and won't need them in the foreseeable future, so I just wanted to make you aware of this. How the plugin resolves this is also up for you to decide:

* Keep the behavior as a "Known Issue", keeping the plugin code as simple as possible.
* Check if bundle.name is defined and issue an error message when it's undefined, generating no manifest
* Generate one manifest per entry point, using the `childBundles` property. This is similar to what I did in #2

**Comment by pierredavidbelanger** [comment]
Good catch! 
You are right, I just tested it.

It seems like the `bundle` we receive (on `'bundled'`) when there is multiple entry points is only a holder that contains the entry point in its `childBundles`. Is this what you observed ?

If yes, it should not be too hard to handle.

I will have a look at this.
